"""Every packaged ado carries a version stamp.

One rule, deliberately: every .ado shipped by datalib.pkg has a `*!` stamp. A
new helper with no stamp is invisible to every other check.

The companion rule -- that a file changed during a release carries a stamp at
least as new as the VERSION then in force -- lives in test_stamps_history.py,
not here. It is split out because it needs real git history to mean anything,
and the public mirror is generated by a fresh init and force-push; run there, it
would demand that every stamp equal the newest version and fail the lot. This
file is safe to ship anywhere.
"""

import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
PKG = ROOT / "datalib.pkg"

STAMP = re.compile(r"^\*!.*?v?(\d+(?:\.\d+){1,2})", re.M)


def git(*args, ok=(0,)):
    r = subprocess.run(["git", "-C", str(ROOT), *args],
                       capture_output=True, text=True, encoding="utf-8",
                       errors="replace")
    return r.stdout.strip() if r.returncode in ok else None


def packaged_ados():
    if not PKG.is_file():
        return []
    out = []
    for line in PKG.read_text(encoding="utf-8").splitlines():
        # both directives ship files: lowercase f for code, capital F for the rest
        if line[:2] in ("f ", "F "):
            rel = line[2:].strip()
            if rel.endswith(".ado"):
                out.append(rel)
    return out


def parse_version(text):
    m = STAMP.search(text)
    if not m:
        return None
    parts = [int(x) for x in m.group(1).split(".")]
    while len(parts) < 3:
        parts.append(0)
    return tuple(parts)


ADOS = packaged_ados()


def test_manifest_lists_ados():
    assert ADOS, "datalib.pkg lists no .ado files -- has the manifest moved?"


@pytest.mark.parametrize("rel", ADOS, ids=ADOS)
def test_every_packaged_ado_has_a_stamp(rel):
    path = ROOT / rel
    assert path.is_file(), f"{rel} is in datalib.pkg but not on disk"
    assert parse_version(path.read_text(encoding="utf-8", errors="replace")), (
        f"{rel} carries no parsable `*!` version stamp"
    )
