*===============================================================================
* qa/run_smoke.do
* -------------------------------------------------------------------------------
* Smoke tests for the api:// backend components (NA-1 .. NA-8 of
* internal/datalib_nada_improvement_plan.md). Everything runs against the
* COMMITTED fixture tree qa/fixtures/api/ through the file:// transport of
* __dtlb_api_read — the same code paths as the network, with no network.
*
* Covered: __dtlb_userhome (all os() branches), __dtlb_credential,
* _dtlb_idno (build/parse/case funnel), _dtlb_catalogregistry (override,
* bundled fallback, consent gate), __dtlb_api_read (200/404/no-credential),
* __dtlb_extensions_probe (info, cache, no-info), _dtlb_catalog REST list
* (capped pagination, parsed + unparsed rows) and files (frame + macros).
*
* Run from the repo root:  stata-mp -b do qa/run_smoke.do
* Exit code: non-zero on any failure (each failed check exits 9).
*===============================================================================

clear all
set more off
version 16

capture log close _all
capture mkdir "qa/logs"
log using "qa/logs/run_smoke.log", replace text

*-- environment ----------------------------------------------------------------
local repo "`c(pwd)'"
adopath ++ "`repo'/src/_"
adopath ++ "`repo'/src/d"
adopath ++ "`repo'/src/i"
adopath ++ "`repo'/src/y"

capture confirm file "`repo'/qa/fixtures/api/info"
if _rc {
    display as error "API fixtures missing (qa/fixtures/api/ is committed — check your clone)"
    exit 9
}

*-- helpers --------------------------------------------------------------------
program drop _all
program define smoke_check
    syntax , cond(string asis) [msg(string)]
    if !(`cond') {
        display as error `"FAIL: `msg'"'
        display as error `"      condition: `cond'"'
        exit 9
    }
    // Count what actually ran, so the closing banner cannot drift from
    // reality. It had been hardcoded at "36 checks" while 48 were defined --
    // harmless only for as long as the suite never reached the banner, which
    // it did not until the fixes in this branch.
    global dtlb_smoke_n = ${dtlb_smoke_n} + 1
    display as result `"PASS: `msg'"'
end

* Legal global name: Stata rejects names beginning with an underscore.
global dtlb_smoke_n = 0

*-- isolated per-user homes ----------------------------------------------------
local home "`repo'/qa/fixtures/_tmp_home"
local ehome "`repo'/qa/fixtures/_tmp_home_empty"
capture mkdir "`home'"
capture mkdir "`ehome'"
* consent_auth_wb matters as much as consent_auth_fxauth: S17 asserts the
* bundled auth entry is REFUSED without consent, and S17b then grants it.
* Leave the marker behind and the next run finds consent already given, so
* S17 passes for the wrong reason.
foreach f in catalogs.yaml consent_auth_fxauth consent_auth_wb audit.log cache/catalogs.yaml cache/catalogs.stamp {
    capture erase "`home'/`f'"
    capture erase "`ehome'/`f'"
}

* Same argument, one level up: __dtlb_extensions_probe caches its capability
* answer in a SESSION GLOBAL (${dtlbext_<hostkey>}), and S24 asserts
* r(probed)==1 -- that the probe was live. -clear all- does not drop globals, so
* a second run inside one Stata session reads the cache, r(probed) is 0, and S24
* fails having proved nothing about probing. That is invisible under `stata -b`,
* where every run is a fresh process, and shows up the moment the suite is run
* twice in one session. Drop the cache so the assertion means what it says.
capture macro drop dtlbext_*

* override registry: fx (no auth) + fxauth (custom auth -> consent gate)
tempname fh
file open `fh' using "`home'/catalogs.yaml", write text replace
file write `fh' "# smoke-test override registry (generated by qa/run_smoke.do)" _n
file write `fh' "fx:" _n
file write `fh' "  name: Fixture Catalog" _n
file write `fh' `"  base_url: file://`repo'/qa/fixtures/api"' _n
file write `fh' "  api_version: v2" _n
file write `fh' "  auth_type: none" _n
file write `fh' "fxauth:" _n
file write `fh' "  name: Fixture Auth Catalog" _n
file write `fh' `"  base_url: file://`repo'/qa/fixtures/api"' _n
file write `fh' "  auth_type: x-api-key" _n
file close `fh'

* credential hygiene: the global must be clear; note a pre-set env token
global datalib_token
local env_token : environment DATALIB_TOKEN
if `"`env_token'"' != "" {
    display as text "note: DATALIB_TOKEN is set in the environment; credential-absence checks are relaxed"
}

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 1 — __dtlb_userhome"
display as text _dup(80) "="
*===============================================================================

__dtlb_userhome
local uh `"`r(datalib_home)'"'
smoke_check, cond(substr(`"`uh'"', -8, .) == ".datalib") msg("S1 default home ends in .datalib")

local henv : environment HOME
if `"`henv'"' != "" {
    __dtlb_userhome, os(Unix)
    smoke_check, cond(`"`r(datalib_home)'"' == `"`henv'/.datalib"') msg("S2 Unix branch uses HOME")
    __dtlb_userhome, os(MacOSX)
    smoke_check, cond(`"`r(datalib_home)'"' == `"`henv'/.datalib"') msg("S3 MacOSX branch uses HOME")
}
else {
    capture __dtlb_userhome, os(Unix)
    local rc = _rc
    smoke_check, cond(`rc' == 198) msg("S2 Unix branch errors cleanly when HOME unset")
    capture __dtlb_userhome, os(MacOSX)
    local rc = _rc
    smoke_check, cond(`rc' == 198) msg("S3 MacOSX branch errors cleanly when HOME unset")
}

local penv : environment USERPROFILE
if `"`penv'"' != "" {
    __dtlb_userhome, os(Windows)
    smoke_check, cond(`"`r(datalib_home)'"' == `"`penv'\.datalib"') msg("S4 Windows branch uses USERPROFILE")
}
else {
    capture __dtlb_userhome, os(Windows)
    local rc = _rc
    smoke_check, cond(`rc' == 198) msg("S4 Windows branch errors cleanly when USERPROFILE unset")
}

capture __dtlb_userhome, os(BeOS)
local rc = _rc
smoke_check, cond(`rc' == 198) msg("S5 unknown os() is an error, never a silent fallback")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 2 — __dtlb_credential"
display as text _dup(80) "="
*===============================================================================

__dtlb_credential, auth_type(none)
smoke_check, cond(`"`r(token)'"' == "") msg("S6 auth_type(none) short-circuits with empty token")

if `"`env_token'"' == "" {
    capture __dtlb_credential, auth_type(x-api-key)
    local rc = _rc
    smoke_check, cond(`rc' == 198) msg("S7 no env var, no global -> error 198")
}
else {
    display as text "SKIP: S7 (DATALIB_TOKEN present in environment)"
}

global datalib_token "smoketest123"
__dtlb_credential, auth_type(bearer)
if `"`env_token'"' == "" {
    smoke_check, cond(`"`r(token)'"' == "smoketest123" & "`r(source)'" == "global") ///
        msg("S8 global credential resolves with source=global")
}
else {
    smoke_check, cond("`r(source)'" == "env") msg("S8 env credential outranks the global")
}
global datalib_token

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 3 — _dtlb_idno (build / parse / case funnel)"
display as text _dup(80) "="
*===============================================================================

_dtlb_idno, country(xaa) year(2015) survey(xhs) version(1)
smoke_check, cond("`r(idno)'" == "XAA_2015_XHS_v01_M" & "`r(folder)'" == "XAA_2015_XHS_v01_M") ///
    msg("S9 build master: one case everywhere -- r(folder) == r(idno)")

local forms `" "1" "01" "v01" "V01" "'
local prev ""
local same = 1
foreach f of local forms {
    _dtlb_idno, country(XAA) year(2015) survey(XHS) version(`f')
    if "`prev'" != "" & "`r(idno)'" != "`prev'" local same = 0
    local prev "`r(idno)'"
}
smoke_check, cond(`same' == 1 & "`prev'" == "XAA_2015_XHS_v01_M") ///
    msg("S10 vintage forms 1/01/v01/V01 build identical identifiers")

_dtlb_idno, country(XAA) year(2015) survey(XHS) version(v01) adaptation(hcl) aversion(V1)
smoke_check, cond("`r(idno)'" == "XAA_2015_XHS_v01_M_v01_A_HCL" & "`r(kind)'" == "adaptation") ///
    msg("S11 build adaptation: collection uppercased, aversion normalised")

capture _dtlb_idno, country(XAA) year(2015) survey(XHS) version(v01) adaptation(HCL)
local rc = _rc
smoke_check, cond(`rc' == 198) msg("S12 adaptation without aversion is refused (never guessed)")

_dtlb_idno, parse("XAA_2015_XHS_v01_M")
smoke_check, cond("`r(country)'" == "XAA" & r(year) == 2015 & "`r(survey)'" == "XHS" ///
    & "`r(version)'" == "v01" & "`r(kind)'" == "master") ///
    msg("S13 parse canonical upper master")

_dtlb_idno, parse("xaa_2015_xhs_v01_m_v01_a_hcl")
smoke_check, cond("`r(country)'" == "XAA" & "`r(adaptation)'" == "HCL" ///
    & "`r(aversion)'" == "v01" & "`r(idno)'" == "XAA_2015_XHS_v01_M_v01_A_HCL") ///
    msg("S14 parse lowercase adaptation -> same tuple, canonical idno")

capture _dtlb_idno, parse("XAA-2022-CUSTOM")
local rc = _rc
smoke_check, cond(`rc' == 198) msg("S15 free-text identifier is a clean parse error")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 4 — _dtlb_catalogregistry"
display as text _dup(80) "="
*===============================================================================

_dtlb_catalogregistry, get(fx) registryhome("`home'") nofetch
smoke_check, cond("`r(source)'" == "user_override" ///
    & `"`r(base_url)'"' == `"file://`repo'/qa/fixtures/api"' ///
    & "`r(auth_type)'" == "none" & r(metadata_only) == 0) ///
    msg("S16 user override resolves fx with source=user_override")

* The bundled registry is located with a bare -findfile catalogs.yaml-, which
* searches PERSONAL, PLUS, SITE and the working directory. A planted file
* therefore resolves as "bundled_fallback", so that source is consent-gated
* too -- it used to resolve auth entries silently. wb declares
* auth_type(x-api-key), so reaching it offline now costs one acceptauth.
capture _dtlb_catalogregistry, get(wb) registryhome("`ehome'") nofetch
local rc = _rc
smoke_check, cond(`rc' == 198) ///
    msg("S17 bundled auth entry without consent is refused (findfile hijack guard)")

_dtlb_catalogregistry, get(wb) registryhome("`ehome'") nofetch acceptauth
smoke_check, cond("`r(source)'" == "bundled_fallback" ///
    & strpos(`"`r(base_url)'"', "microdata.worldbank.org") > 0 ///
    & "`r(auth_type)'" == "x-api-key") ///
    msg("S17b bundled registry resolves wb once consent is given")

capture _dtlb_catalogregistry, get(nosuchcatalog) registryhome("`ehome'") nofetch
local rc = _rc
smoke_check, cond(`rc' == 198) msg("S18 unknown catalog errors with 198")

capture _dtlb_catalogregistry, get(fxauth) registryhome("`home'") nofetch
local rc = _rc
smoke_check, cond(`rc' == 198) msg("S19 custom auth entry without consent is refused (R-B)")

_dtlb_catalogregistry, get(fxauth) registryhome("`home'") nofetch acceptauth
smoke_check, cond("`r(auth_type)'" == "x-api-key" & "`r(source)'" == "user_override") ///
    msg("S20a acceptauth grants one-time consent")
_dtlb_catalogregistry, get(fxauth) registryhome("`home'") nofetch
smoke_check, cond("`r(auth_type)'" == "x-api-key") msg("S20b consent is remembered (marker file)")
capture confirm file "`home'/audit.log"
local rc = _rc
smoke_check, cond(`rc' == 0) msg("S20c consent is logged to audit.log")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 5 — __dtlb_api_read (file:// transport)"
display as text _dup(80) "="
*===============================================================================

__dtlb_api_read using "file://`repo'/qa/fixtures/api/catalog/find_by_idno/XAA_2015_XHS_v01_M.json"
local body `"`r(body_path)'"'
smoke_check, cond(r(status_code) == 200 & "`r(content_type)'" == "application/json") ///
    msg("S21a fixture GET returns 200 + application/json")
capture confirm file `"`body'"'
local rc = _rc
smoke_check, cond(`rc' == 0) msg("S21b body file exists and survives the call")
capture erase `"`body'"'

__dtlb_api_read using "file://`repo'/qa/fixtures/api/catalog/find_by_idno/ZZA_1990_NOPE_v01_M.json"
smoke_check, cond(r(status_code) == 404) msg("S22 missing fixture maps to 404")

* no token anywhere (global cleared above); auth_type would need one on the
* network path — file:// must not even look
__dtlb_api_read using "file://`repo'/qa/fixtures/api/info", auth_type(x-api-key)
smoke_check, cond(r(status_code) == 200) msg("S23 file:// never consults credentials")
capture erase `"`r(body_path)'"'

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 6 — __dtlb_extensions_probe"
display as text _dup(80) "="
*===============================================================================

__dtlb_extensions_probe, host("file://`repo'/qa/fixtures/api")
smoke_check, cond("`r(nada_api)'" == "v2" & `"`r(extensions)'"' == "audit-v1 token-v1" & r(probed) == 1) ///
    msg("S24 /info fixture yields nada_api + extensions")

__dtlb_extensions_probe, host("file://`repo'/qa/fixtures/api")
smoke_check, cond(r(probed) == 0 & `"`r(extensions)'"' == "audit-v1 token-v1") ///
    msg("S25 second probe is served from the session cache")

__dtlb_extensions_probe, host("file://`repo'/qa/fixtures/api/catalog")
smoke_check, cond(`"`r(extensions)'"' == "" & "`r(nada_api)'" == "") ///
    msg("S26 host without /info -> empty extensions, not an error")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 7 — _dtlb_catalog, list catalog() (NA-5)"
display as text _dup(80) "="
*===============================================================================

_dtlb_catalog, list catalog(fx) registryhome("`home'") nofetch
smoke_check, cond(r(rows_found) == 250 & r(rows_returned) == 3 & r(pages_fetched) == 1 ///
    & r(more_pages_available) == 1 & r(status_code) == 200) ///
    msg("S27a capped pagination: 1 page, more available, honest r() counts")
smoke_check, cond(r(N) == 3) msg("S27b r(N) mirrors rows_returned")

frame dtlb_catalog: quietly count
smoke_check, cond(r(N) == 3) msg("S27c frame holds exactly the fetched rows")

frame dtlb_catalog: quietly count if idno == "XAA_2015_XHS_v01_M" & kind == "master" ///
    & country == "XAA" & year == 2015 & survey == "XHS" & version == "v01" & source == "api:fx"
smoke_check, cond(r(N) == 1) msg("S28a master row parsed through the idno funnel")

frame dtlb_catalog: quietly count if idno == "XAA_2015_XHS_v01_M_v01_A_HCL" ///
    & kind == "adaptation" & adaptation == "HCL" & aversion == "v01"
smoke_check, cond(r(N) == 1) msg("S28b adaptation row parsed with collection + aversion")

frame dtlb_catalog: quietly count if idno == "XAA-2022-CUSTOM" & country == "" ///
    & year == 2022 & title != ""
smoke_check, cond(r(N) == 1) msg("S29 non-conforming idno kept as unparsed row (year from year_start)")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 8 — _dtlb_catalog, files (NA-6)"
display as text _dup(80) "="
*===============================================================================

_dtlb_catalog, files catalog(fx) idno(xaa_2015_xhs_v01_m) registryhome("`home'") nofetch
smoke_check, cond("`r(idno)'" == "XAA_2015_XHS_v01_M") ///
    msg("S30a lowercase idno() input goes out canonical (case funnel)")
smoke_check, cond(r(n_files) == 3 & r(has_stata) == 1 & r(total_bytes) == 55574528) ///
    msg("S30b summary scalars: n_files, has_stata, total_bytes")
smoke_check, cond("`r(file_1_name)'" == "xaa_2015_xhs_v01_m_household.dta" & r(file_1_size) == 52428800) ///
    msg("S30c r() macros mirror the first files")
smoke_check, cond("`r(frame)'" == "dtlb_files") msg("S30d frame name returned")

frame dtlb_files: quietly count
smoke_check, cond(r(N) == 3) msg("S30e dtlb_files holds the complete list")
frame dtlb_files: quietly count if file_format == "application/x-stata-dta" & file_size == 52428800
smoke_check, cond(r(N) == 1) msg("S30f file columns populated from the response")

capture _dtlb_catalog, files catalog(fx) idno(ZZA_1990_NOPE_v01_M) registryhome("`home'") nofetch
local rc = _rc
smoke_check, cond(`rc' == 601) msg("S31 unknown survey -> not-found error 601")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 9 — clear"
display as text _dup(80) "="
*===============================================================================

_dtlb_catalog, clear
capture frame dtlb_catalog: quietly count
local rc1 = _rc
capture frame dtlb_files: quietly count
local rc2 = _rc
smoke_check, cond(`rc1' != 0 & `rc2' != 0) msg("S32 clear drops both frames")

*===============================================================================
display _newline as text _dup(80) "="
display as text "SECTION 10 — generated demo library (datalib_makelib)"
display as text _dup(80) "="
*===============================================================================

* The library is built here rather than read from the repository. Committing a
* library made this suite depend on tracked microdata, which is the thing the
* repository is moving away from; generating it keeps the same inventory --
* 8 versions, 6 masters, 2 adaptations, 5 of them carrying datalib.yaml -- so
* the assertions below are unchanged.
tempfile demostub
local demobase = subinstr("`demostub'", "\", "/", .)
capture mkdir "`demobase'_demo"
local DEMOLIB "`demobase'_demo/datalib"
datalib_makelib, path("`DEMOLIB'") families(demo) quietly

_dtlb_catalog, scan path("`DEMOLIB'")
smoke_check, cond(r(n_versions) == 8 & r(n_masters) == 6 & r(n_adaptations) == 2) ///
    msg("S33 generated library scans: 8 versions = 6 masters + 2 adaptations")

frame dtlb_catalog: quietly count
smoke_check, cond(r(N) == 8) msg("S34 catalog frame holds the 8 generated rows")

frame dtlb_catalog: quietly count if has_yaml == 1
smoke_check, cond(r(N) == 5) msg("S35 five masters carry datalib.yaml (XAA XHS v02 deliberately without)")

frame dtlb_catalog: quietly count if has_yaml == 1 & producer != ""
smoke_check, cond(r(N) == 5) msg("S36 YAML metadata extracted: producer populated on all five")

_dtlb_catalog, clear

*===============================================================================
display _newline as text _dup(80) "="
display as result "ALL SMOKE TESTS PASSED (${dtlb_smoke_n} checks across NA-1 .. NA-8 + demo library)"
display as text _dup(80) "="

log close
exit 0
